import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Link from "next/link";

const steps = [
  { num: "01", title: "Lead submits a form", desc: "A prospective client fills out your inquiry form on your website." },
  { num: "02", title: "Instant personalized outreach", desc: "Ivedian sends a tailored SMS and email within 2 minutes — written by AI, sounding human." },
  { num: "03", title: "7-day nurture sequence", desc: "Four follow-ups fire automatically over the next week, each aware of what was already sent." },
  { num: "04", title: "You stay informed", desc: "A daily summary email shows new leads, messages sent, and pipeline status every morning." },
];

const features = [
  { title: "AI-written messages", desc: "Every message is generated by Claude AI and personalized to the lead's name, service interest, and history." },
  { title: "SMS + Email", desc: "Reaches leads on both channels. Respects opt-outs automatically when a lead replies STOP." },
  { title: "Read-only dashboard", desc: "See every lead, their status, and message history at a glance — no login required." },
  { title: "30-day free trial", desc: "Try Ivedian free for 30 days with up to 75 leads. No credit card required to start." },
  { title: "Zero setup friction", desc: "One webhook in your inquiry form. We handle the rest — no CRM, no complex integrations." },
  { title: "Daily summary email", desc: "An 8am digest lands in your inbox every morning with new leads and pipeline activity." },
];

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col">
      <Nav />

      {/* Hero */}
      <section className="max-w-3xl mx-auto mt-24 mb-20 px-6 text-center">
        <h1 className="text-5xl font-extrabold tracking-tight leading-tight mb-6">
          Every med spa inquiry<br />deserves an{" "}
          <span className="text-blue-600">instant reply</span>
        </h1>
        <p className="text-lg text-gray-500 max-w-xl mx-auto mb-10">
          Ivedian sends a personalized SMS and email to every new lead within 2 minutes — then follows up automatically for 7 days so you never lose a booking to slow response times.
        </p>
        <Link
          href="/contact"
          className="inline-block bg-gray-900 text-white px-8 py-3.5 rounded-md text-sm font-semibold hover:bg-blue-600 transition-colors"
        >
          Get early access
        </Link>
      </section>

      {/* How it works */}
      <section className="max-w-4xl mx-auto mb-24 px-6" id="how-it-works">
        <p className="text-xs font-bold tracking-widest uppercase text-blue-600 mb-3">How it works</p>
        <h2 className="text-3xl font-extrabold tracking-tight mb-12">Set up once. Follow up forever.</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {steps.map((s) => (
            <div key={s.num} className="border border-gray-200 rounded-xl p-7">
              <div className="text-xs font-bold text-blue-600 mb-2.5">{s.num}</div>
              <h3 className="text-sm font-bold mb-2">{s.title}</h3>
              <p className="text-sm text-gray-500 leading-relaxed">{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="max-w-4xl mx-auto mb-24 px-6">
        <p className="text-xs font-bold tracking-widest uppercase text-blue-600 mb-3">Features</p>
        <h2 className="text-3xl font-extrabold tracking-tight mb-12">Built for med spa owners.</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((f) => (
            <div key={f.title} className="bg-gray-50 rounded-xl p-6">
              <h3 className="text-sm font-bold mb-1.5">{f.title}</h3>
              <p className="text-sm text-gray-500 leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <div className="mt-auto">
        <Footer />
      </div>
    </div>
  );
}
