import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service — Ivedian" };

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col">
      <Nav />
      <div className="max-w-2xl mx-auto mt-16 mb-24 px-6 flex-1">
        <p className="text-xs font-bold tracking-widest uppercase text-blue-600 mb-3">Legal</p>
        <h1 className="text-4xl font-extrabold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-12">Last updated: March 15, 2025</p>

        <p className="text-sm text-gray-600 mb-4">These Terms of Service ("Terms") govern your access to and use of the Ivedian platform and services ("Service") provided by Ivedian ("we," "us," or "our"). By accessing or using the Service, you agree to be bound by these Terms.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">1. Definitions</h2>
        <ul className="list-disc ml-5 mb-4 text-sm text-gray-600 space-y-1">
          <li><strong>"Customer"</strong> means a business (such as a medical spa) that has signed up to use the Service.</li>
          <li><strong>"End User"</strong> means a prospective client of the Customer whose contact information is submitted to the Service via a webhook or inquiry form.</li>
          <li><strong>"Service"</strong> means Ivedian's automated lead follow-up platform, including SMS and email delivery, AI message generation, scheduling, and dashboard features.</li>
        </ul>

        <h2 className="text-lg font-bold mt-10 mb-3">2. Eligibility</h2>
        <p className="text-sm text-gray-600 mb-4">You must be at least 18 years old and have the legal authority to enter into these Terms on behalf of your business. By using the Service, you represent that you meet these requirements.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">3. Account and Access</h2>
        <p className="text-sm text-gray-600 mb-4">Customers are provisioned by Ivedian and receive a unique dashboard token and webhook endpoint. You are responsible for keeping your credentials secure. You must notify us immediately at <a href="mailto:hello@ivedian.com" className="text-blue-600 hover:underline">hello@ivedian.com</a> if you suspect unauthorized access.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">4. Trial Period</h2>
        <p className="text-sm text-gray-600 mb-4">New Customers receive a 30-day free trial with a cap of 75 leads. No credit card is required to start. At the end of the trial period, the account will be paused until a paid plan is activated. We reserve the right to modify trial terms with reasonable notice.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">5. Acceptable Use</h2>
        <p className="text-sm text-gray-600 mb-2">You agree to use the Service only for lawful purposes. You must not:</p>
        <ul className="list-disc ml-5 mb-4 text-sm text-gray-600 space-y-1">
          <li>Submit contact information for individuals who have not consented to receive marketing communications</li>
          <li>Use the Service to send spam, unsolicited messages, or messages unrelated to the lead's original inquiry</li>
          <li>Misrepresent your identity or business in messages sent through the Service</li>
          <li>Violate any applicable law, including the Telephone Consumer Protection Act (TCPA), CAN-SPAM Act, or state equivalents</li>
          <li>Attempt to reverse engineer, copy, or resell the Service</li>
        </ul>

        <h2 className="text-lg font-bold mt-10 mb-3">6. SMS Messaging and Compliance</h2>
        <p className="text-sm text-gray-600 mb-2">By using the Service's SMS features, you represent and warrant that:</p>
        <ul className="list-disc ml-5 mb-4 text-sm text-gray-600 space-y-1">
          <li>All End Users whose phone numbers you submit have provided prior express written consent to receive automated SMS messages from your business</li>
          <li>Your inquiry forms include appropriate consent language disclosing that submitting the form may result in automated SMS follow-up</li>
          <li>You will honor all opt-out requests (STOP replies) promptly</li>
        </ul>
        <p className="text-sm text-gray-600 mb-4">Ivedian is not responsible for TCPA violations or carrier penalties arising from your failure to obtain proper consent.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">7. AI-Generated Content</h2>
        <p className="text-sm text-gray-600 mb-4">Messages sent through the Service are generated by Anthropic's Claude AI model. While we take steps to produce appropriate content, you acknowledge that AI-generated content may occasionally be imperfect. You remain responsible for the messages sent on your behalf through the Service.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">8. Data and Privacy</h2>
        <p className="text-sm text-gray-600 mb-4">Your use of the Service is also governed by our <Link href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>. You are responsible for ensuring you have the legal right to submit End User data to our Service and that your own privacy policy covers the use of third-party follow-up tools.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">9. Intellectual Property</h2>
        <p className="text-sm text-gray-600 mb-4">We retain all rights to the Service, including its software, design, and underlying technology. These Terms do not grant you any ownership interest in the Service.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">10. Termination</h2>
        <p className="text-sm text-gray-600 mb-4">We may suspend or terminate your account at any time if we determine you have violated these Terms. You may request account termination at any time by contacting <a href="mailto:hello@ivedian.com" className="text-blue-600 hover:underline">hello@ivedian.com</a>. Upon termination, your data will be deleted within 30 days.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">11. Disclaimers</h2>
        <p className="text-sm text-gray-600 mb-4">The Service is provided "as is" without warranties of any kind, express or implied. We do not guarantee that the Service will be uninterrupted, error-free, or that every lead will receive messages successfully. SMS delivery is subject to carrier conditions outside our control.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">12. Limitation of Liability</h2>
        <p className="text-sm text-gray-600 mb-4">To the maximum extent permitted by law, Ivedian's total liability to you for any claim arising from or related to the Service shall not exceed the amount you paid us in the 3 months preceding the claim. We are not liable for indirect, incidental, consequential, or punitive damages.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">13. Indemnification</h2>
        <p className="text-sm text-gray-600 mb-4">You agree to indemnify and hold harmless Ivedian, its officers, and employees from any claims, damages, or expenses (including legal fees) arising from your use of the Service, violation of these Terms, or violation of any third-party rights.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">14. Governing Law</h2>
        <p className="text-sm text-gray-600 mb-4">These Terms are governed by the laws of the State of Texas, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Travis County, Texas.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">15. Changes to These Terms</h2>
        <p className="text-sm text-gray-600 mb-4">We may update these Terms from time to time. We will post the updated Terms on this page with a revised "Last updated" date. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>

        <h2 className="text-lg font-bold mt-10 mb-3">16. Contact</h2>
        <p className="text-sm text-gray-600 mb-2">Questions about these Terms? Contact us at:</p>
        <p className="text-sm text-gray-600">
          Ivedian<br />
          5900 Balcones Drive Suite 100<br />
          Austin, TX 78731<br />
          <a href="mailto:hello@ivedian.com" className="text-blue-600 hover:underline">hello@ivedian.com</a>
        </p>
      </div>
      <Footer />
    </div>
  );
}
